// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI98xwG4BfaifphRsRO8gSLO756LQ4k-4',
    appId: '1:477207944580:web:e994da4bd84894b97351d1',
    messagingSenderId: '477207944580',
    projectId: 'simple-coin-44e16',
    authDomain: 'simple-coin-44e16.firebaseapp.com',
    storageBucket: 'simple-coin-44e16.appspot.com',
    measurementId: 'G-53DMVTDY4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg1QGn5JClbx0T39GzSBiZf-iKtZZB8Rg',
    appId: '1:477207944580:android:93d8e44e48de5d507351d1',
    messagingSenderId: '477207944580',
    projectId: 'simple-coin-44e16',
    storageBucket: 'simple-coin-44e16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Kp4-e9zCm8RPr8i1QUcLq48D4YgXusQ',
    appId: '1:477207944580:ios:7af99ec567a9f0157351d1',
    messagingSenderId: '477207944580',
    projectId: 'simple-coin-44e16',
    storageBucket: 'simple-coin-44e16.appspot.com',
    iosBundleId: 'com.example.simpleCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Kp4-e9zCm8RPr8i1QUcLq48D4YgXusQ',
    appId: '1:477207944580:ios:b5095e67e6ca7afc7351d1',
    messagingSenderId: '477207944580',
    projectId: 'simple-coin-44e16',
    storageBucket: 'simple-coin-44e16.appspot.com',
    iosBundleId: 'com.example.simpleCoin.RunnerTests',
  );
}
